### PR TITLE
new function type

### PR DESCRIPTION
**Pull request by rvignolo**
please, check out the changes for `call_t` and `loadable_routine_t` as well

### CODE REVIEW

**Comment by gtheler** [comment]
at first I thoguht this is what you wanted to do and hence I said "no" then I re-read and understood that you wanted to _add_ a new type instead of changing the current one so I wanted to take a look

I cannot accept this but I might accept a new function type with the prototype you propose

**Comment by gtheler** [comment]
do not pass the function name, pass a pointer to void to the new function name

**Comment by gtheler** [comment]
and try to figure out another name for the enum, like routine_with_params or something like that, do not use the word plugin

**Comment by rvignolo** [comment]
do you mean something like:
```C
struct function_t {
  char *name;
  int initialized;
  
  // ...
  enum  {
    type_undefined,
    type_algebraic,
    type_pointwise_data,
    type_pointwise_file,
    type_pointwise_vector,
    type_pointwise_mesh_property,
    type_pointwise_mesh_node,
    type_pointwise_mesh_cell,
    type_routine,
    type_routine_params,
  } type;
  // ...
  void *params;
  double (*routine_params)(const double *, void *);
```
and then, when calling `wasora_evaluate_function` use:
```C
} else if (function->type == type_routine_params) {
    y = function-> routine_params(x, function->params);
```

**Comment by gtheler** [comment]
yes

do you need to add the params to function_t?

**Comment by rvignolo** [comment]
yes, somehow when I make the call to `routine_params` I have to be able to get an object with parameters. 

the first approach is to search the object by name in a hash table. so what I could do is split the function name and take the last part after the underscore and that is going to be the object name. this is what I proposed in the current scheme, i.e.:
```C
 y = function-> routine_params(x, function->name);
```
The other approach is to point the void pointer in the `function_t` structure to the object instead of searching by name in the routine. The routine call will be:
```C
y = function-> routine_params(x, function->params);
```
Finally, in the routine function I just have to cast it accordingly, i.e.:
```C
object_t *object = (object_t *) params;
```
I think the last approach is better

**Pull request merged**
